import { createSlice } from "@reduxjs/toolkit";
const counterSlice = createSlice({
  name: "counter", // Name of the slice
  initialState: {
    value: 0, // Initial state for the counter
  },
  reducers: {
    increment: (state) => {
      state.value += 1; // Action to increment the counter
    },
    decrement: (state) => {
      state.value > 0 ? (state.value -= 1) : initialState; // Action to decrement the counter
    },
    reset: (state) => {
      state.value = 0; // Action to reset the counter
    },
  },
});

// Export the actions generated by createSlice
export const { increment, decrement, reset } = counterSlice.actions;
// Export the reducer to be used in the store
export default counterSlice.reducer;
